books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books, name='books'),
    path('readJSON/<str:query>/', views.readJSON, name='readJSON'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('books/', include('books.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/',views.userLogin,name='login'),
    path('register/',views.userRegister,name='register'),
    path('logout/',views.userLogout,name='logout'),
]

books/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','type': 'password','placeholder':'********'}))
    class Meta():
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control','type': 'text','placeholder':'exampleuser'}),
            'email': forms.EmailInput(attrs={'class': 'form-control','type': 'email','required':'True','placeholder':'example@gmail.com'})
        }

books/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests

def books(request):
    return render(request, 'books.html')

def readJSON(request,query):
    if request.user.is_authenticated:
        googlebooks = 'https://www.googleapis.com/books/v1/volumes?q='
        url = googlebooks + query
        json_data = json.loads(requests.get(url).text)
        return JsonResponse(json_data)
    if not request.user.is_authenticated:
        return render(request, 'books.html')

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import UserForm

def userLogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user) # Saves the user’s ID in the session using Django’s session framework
            return redirect('/')
        else:
            return render(request, 'login.html', {'failed':True})
    else:
        return render(request, 'login.html', {'failed':False})

def userRegister(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
    else:
        user_form = UserForm()
    return render(request, 'register.html', {'user_form': user_form, 'registered': registered})

@login_required
def userLogout(request):
    logout(request) # Session data will be completely cleaned out
    return redirect('/')

books/templates/books.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Book{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'books.css' %}">
{% endblock additional_css %}

{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock js %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4" id="book">BOOK &#128214</h1>
            <p class="lead" id = "find">Find your books here</p>
        </div>
    </div>
    <br>
    {% if user.is_authenticated %} 
        <div class="container-fluid">
            <div class = "row">
                <div class="d-flex flex-row col sm-12" id="form">
                    <input id='search_input' class="form-control" type="text" placeholder="Search for books name or author here">
                    <div class="input-group-prepend">
                        <button type="submit" class="btn btn-primary" id="buttonSubmit">SEARCH</button>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 table-wrapper-scroll-y my-custom-scrollbar">
                    <table class="table" width="100%">
                        <thead class="text-center">
                        <tr>
                            <th width="15%">Cover</th>
                            <th width="30%">Title</th>
                            <th width="20%">Author</th>
                            <th width="20%">Publisher</th>
                            <th width="15%">Read Here</th>
                        </tr>
                        </thead>
                        <tbody id="table-books" class="text-center">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endif %}
    {% if not user.is_authenticated %}
        <div class = "container-fluid" id = "warning">
            <h2>&#128226 Login First, Please &#128226</h2>
        </div>
    {% endif %}
{% endblock content %}

{% block script %}<script src="{% static 'books.js' %}"></script>{% endblock script %}

main/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'styles_main.css' %}">
{% endblock additional_css %}

{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock js %}

{% block content %}
<div class="jumbotron-fluid">
    <div class="container-fluid" id = "csatu">
        <div class="row align-items-center justify-content-center">
            <div class="col-sm-12 judul">
                <h1 align="center" class = "display-4"><b style="font-weight: bold;">Home &#127969</b></h1>
                <hr align="center" width="50%">
                <h2 align="center"><b>Siapa sih Efrin?</b></h2>
            </div>
            <div class="col-sm-12">
                <div class="container" id = "biodata">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-sm-12 col-md-4">
                            <img src="{% static 'efrin.jpg' %}" width="200px" style="display: inline-flexbox;border-radius: 50%; border: 7px solid black;">
                        </div>
                        <div class="col-sm-12 col-md-8">
                            <table>
                                <tr><td><b>Nama</b></td> <td>:</td> <td>Sefrina Fauranisa</td></tr>
                                <tr><td><b>NPM</b></td> <td>:</td> <td>1906398944</td></tr>
                                <tr><td><b>Angkatan</b></td> <td>:</td> <td>2019</td></tr>
                                <tr><td><b>Hobi</b></td> <td>:</td> <td>Tidak pasti</td></tr>
                                <tr><td><b>Tempat Kuliah</b></td> <td>:</td> <td>Universitas Indonesia</td></tr>
                                <tr><td><b>Deskripsi Tentang Saya</b></td> <td>:</td> <td>Pemalas yang berpura-pura tidak malas</td></tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container accord">
            <div class="accor1 accordion">
                <h3>Aktivitas <span><button class="up">up</button><button class="down">down</button></span></h3>
                <div class="panel1 panel">
                    <p>Makan</p>
                    <p>Tidur</p>
                    <p>Ngedrakor</p>
                </div>
            </div>

            <div class="accor2 accordion">
                <h3>Organisasi <span><button class="up">up</button><button class="down">down</button></span></h3>
                <div class="panel2 panel">
                    <p>BEM Fasilkom 2019</p>
                    <p>FUKI 2019</p>
                </div>
            </div>

            <div class="accor3 accordion">
                <h3>Kepanitiaan <span><button class="up">up</button><button class="down">down</button></span></h3>
                <div class="panel3 panel">
                    <p>SIWAK NG 2019</p>
                    <p>BETIS 2019</p>
                </div>
            </div>

            <div class="accor4 accordion">
                <h3>Prestasi <span><button class="up">up</button><button class="down">down</button></span></h3>
                <div class="panel4 panel">
                    <p>Juara 1 Tari Saman Jabodetabek</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
    <script src="{% static 'story7.js' %}"></script>
{% endblock script%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title%}Base{% endblock title %}</title>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'story/styles.css' %}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  {% block additional_css %}
  {% endblock additional_css %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  {% block js %}
  {% endblock js %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'main:home' %}">efrin.frn</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:home' %}" id = "link">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'books:books' %}" id = "link">Book <span class="sr-only">(current)</span></a>
            </li>
          </ul>
      {% if user.is_authenticated %}
        <ul class="navbar-nav navbar-right">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:logout' %}" id = "link">Logout <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" id = "sapa">Hallo, {{ user.username }}!</a>
          </li>
        </ul>
      {% else %}
        <ul class="navbar-nav navbar-right">
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:register' %}" id = "link">Register <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:login' %}" id = "link">Login <span class="sr-only">(current)</span></a>
          </li>
        </ul>
    {% endif %}
      </div>
  </nav>
  
  {% block content %}
  {% endblock content %}
  {% block script %}
  {% endblock script%}
</body>

</html>

user/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Login{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'users.css' %}">
{% endblock additional_css %}

{% block content %}
    <div class="jumbotron jumbotron-fluid" id = "gambar">
        <div class="container">
            <h1 class="display-4" id="judul">LOGIN &#128071</h1>
            <p class="lead" id = "par">Login your account here</p>
        </div>
    </div>
    <div class="container-fluid">
        {% if failed %}
            <h4 id="invalid">Invalid username or password!</h4>
        {% endif %}
        <div class = "container-fluid" id = "form">
            <form method="post" action="{% url 'user:login' %}">
                {% csrf_token %}
                <p><label for="id_username">Username</label>
                    <input type="text" name="username" class="form-control" placeholder="Masukkan username kamu disini" id="id_username"></p>
                <p><label for="id_password">Password</label>
                    <input type="password" name="password" class="form-control" placeholder="Masukkan password kamu disini" id="id_password"></p>
                <input type="submit" value="Login" id="buttonLogin">
            </form>
        </div>
    </div>
{% endblock content %}

user/templates/register.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Register{% endblock %}
{% block additional_css %}
    <link rel="stylesheet" href="{% static 'users.css' %}">
{% endblock additional_css %}

{% block content %}
    <div class="jumbotron jumbotron-fluid" id = "gambar1">
        <div class="container">
            <h1 class="display-4" id="judul">REGISTER &#128203</h1>
            <p class="lead" id = "par">Register your account here</p>
        </div>
    </div>
    <div class = "container-fluid" id = "form">
        {% if registered %}
            efrin.frn says "thank you for registering" &#128077
        {% else %}
        <div class="container">
            <div class="col">
                <form method="POST">
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    <input type="submit" value="Register" id="buttonLogin">
                </form>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock content %}